### ISSUE TITLE
go-test failures

### ISSUE THREAD

**Issue by danbryan** [bryanlabs/cosmos-tax-cli#113]
There is a list of pre-commit standards I like to use for go apps.  Right now its failing on my go-test hooks.  @davidkonigsberg I know you do some go testing on the CSV and osmosis folder in your workflow.  Do you think it's worth addressing these other issues my tooling found?

```
# Go Test
-   id: go-test-mod
-   id: go-test-repo-mod
```
I get 

```
check yaml...............................................................Passed
fix end of files.........................................................Passed
trim trailing whitespace.................................................Passed
check for case conflicts.................................................Passed
check for merge conflicts................................................Passed
check for added large files..............................................Passed
detect private key.......................................................Passed
go-fmt...................................................................Passed
go-fmt-repo..............................................................Passed
go-build-mod.............................................................Passed
go-build-repo-mod........................................................Passed
go-mod-tidy..............................................................Passed
go-mod-tidy-repo.........................................................Passed
go-test-mod..............................................................Failed
- hook id: go-test-mod
- exit code: 1

2022/11/06 12:12:29 proto: duplicate proto type registered: ibc.applications.transfer.v1.DenomTrace
2022/11/06 12:12:29 proto: duplicate proto type registered: ibc.applications.transfer.v1.Params
2022/11/06 12:12:29 proto: duplicate proto type registered: ibc.applications.transfer.v1.MsgTransfer
2022/11/06 12:12:29 proto: duplicate proto type registered: ibc.applications.transfer.v1.MsgTransferResponse
--- FAIL: TestCosmosHubAddressEquality (0.00s)
    backend_test.go:25: Addresses not equivalent invalid Bech32 prefix; expected osmo, got cosmos invalid Bech32 prefix; expected osmovaloper, got cosmosvaloper
--- FAIL: TestCosmosAllAddressEquality (0.00s)
    backend_test.go:37: Addresses not equivalent <nil> <nil>
FAIL
FAIL    github.com/DefiantLabs/cosmos-tax-cli-private   0.033s
?       github.com/DefiantLabs/cosmos-tax-cli-private/client    [no test files]
?       github.com/DefiantLabs/cosmos-tax-cli-private/cmd       [no test files]
?       github.com/DefiantLabs/cosmos-tax-cli-private/config    [no test files]
?       github.com/DefiantLabs/cosmos-tax-cli-private/core      [no test files]
?       github.com/DefiantLabs/cosmos-tax-cli-private/cosmos/modules    [no test files]
?       github.com/DefiantLabs/cosmos-tax-cli-private/cosmos/modules/bank       [no test files]
?       github.com/DefiantLabs/cosmos-tax-cli-private/cosmos/modules/denoms     [no test files]
?       github.com/DefiantLabs/cosmos-tax-cli-private/cosmos/modules/distribution       [no test files]
?       github.com/DefiantLabs/cosmos-tax-cli-private/cosmos/modules/ibc        [no test files]
?       github.com/DefiantLabs/cosmos-tax-cli-private/cosmos/modules/ibc/types  [no test files]
?       github.com/DefiantLabs/cosmos-tax-cli-private/cosmos/modules/staking    [no test files]
?       github.com/DefiantLabs/cosmos-tax-cli-private/cosmos/modules/tx [no test files]
ok      github.com/DefiantLabs/cosmos-tax-cli-private/csv       (cached)
?       github.com/DefiantLabs/cosmos-tax-cli-private/csv/parsers       [no test files]
?       github.com/DefiantLabs/cosmos-tax-cli-private/csv/parsers/accointing    [no test files]
?       github.com/DefiantLabs/cosmos-tax-cli-private/db        [no test files]
?       github.com/DefiantLabs/cosmos-tax-cli-private/osmosis   [no test files]
ok      github.com/DefiantLabs/cosmos-tax-cli-private/osmosis/modules/gamm      (cached)
?       github.com/DefiantLabs/cosmos-tax-cli-private/rest      [no test files]
2022/11/06 12:12:29 proto: duplicate proto type registered: ibc.applications.transfer.v1.DenomTrace
2022/11/06 12:12:29 proto: duplicate proto type registered: ibc.applications.transfer.v1.Params
2022/11/06 12:12:29 proto: duplicate proto type registered: ibc.applications.transfer.v1.MsgTransfer
2022/11/06 12:12:29 proto: duplicate proto type registered: ibc.applications.transfer.v1.MsgTransferResponse
2022/11/06 12:12:29 /home/socket/.lens
2022/11/06 12:12:29 Error getting account from key or address:  default
2022/11/06 12:12:29 /home/socket/.lens
goroutine 16 [running]:
runtime/debug.Stack()
        /usr/lib/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /usr/lib/go/src/runtime/debug/stack.go:16 +0x19
github.com/cosmos/cosmos-sdk/codec/types.anyCompatError({0x18edd2b, 0xc}, {0x18b2240, 0xc00027c300})
        /home/socket/go/pkg/mod/github.com/osmosis-labs/cosmos-sdk@v0.45.1-0.20220502203419-5831ca02b81f/codec/types/compat.go:24 +0x3f
github.com/cosmos/cosmos-sdk/codec/types.(*Any).MarshalJSON(0x18b2240?)
        /home/socket/go/pkg/mod/github.com/osmosis-labs/cosmos-sdk@v0.45.1-0.20220502203419-5831ca02b81f/codec/types/compat.go:56 +0x56
encoding/json.marshalerEncoder(0xc00109aa00, {0x18b2240?, 0xc00062c098?, 0x185a0a0?}, {0xc0?, 0x2f?})
        /usr/lib/go/src/encoding/json/encode.go:478 +0xbe
encoding/json.arrayEncoder.encode({0xc0015ddb10?}, 0xc00109aa00, {0x1641be0?, 0xc00027c2a0?, 0x16ad130?}, {0xa?, 0x0?})
        /usr/lib/go/src/encoding/json/encode.go:915 +0xd5
encoding/json.sliceEncoder.encode({0x40f85f?}, 0xc00109aa00, {0x1641be0?, 0xc00027c2a0?, 0x7fd6a3e7ffff?}, {0xb?, 0x0?})
        /usr/lib/go/src/encoding/json/encode.go:888 +0x367
encoding/json.structEncoder.encode({{{0xc001102000?, 0x1?, 0x0?}, 0xc001506b10?}}, 0xc00109aa00, {0x17ebfe0?, 0xc00027c2a0?, 0x10?}, {0x0, 0x1})
        /usr/lib/go/src/encoding/json/encode.go:760 +0x1f4
encoding/json.ptrEncoder.encode({0x175ace0?}, 0xc00109aa00, {0x1892740?, 0xc0015063f0?, 0x3?}, {0x7?, 0x0?})
        /usr/lib/go/src/encoding/json/encode.go:944 +0x25e
encoding/json.structEncoder.encode({{{0xc0010f3200?, 0x0?, 0x0?}, 0xc001506e70?}}, 0xc00109aa00, {0x17941e0?, 0xc0015063f0?, 0x0?}, {0x0, 0x1})
        /usr/lib/go/src/encoding/json/encode.go:760 +0x1f4
encoding/json.ptrEncoder.encode({0xc0015c13e0?}, 0xc00109aa00, {0x18ab880?, 0xc001212200?, 0x7?}, {0x30?, 0x0?})
        /usr/lib/go/src/encoding/json/encode.go:944 +0x25e
encoding/json.arrayEncoder.encode({0x8?}, 0xc00109aa00, {0x16420e0?, 0xc0015d0600?, 0xc0015ddb08?}, {0x86?, 0x16?})
        /usr/lib/go/src/encoding/json/encode.go:915 +0xd5
encoding/json.sliceEncoder.encode({0x4690da?}, 0xc00109aa00, {0x16420e0?, 0xc0015d0600?, 0xc00109aa00?}, {0x6?, 0x0?})
        /usr/lib/go/src/encoding/json/encode.go:888 +0x367
encoding/json.structEncoder.encode({{{0xc0010f2fc0?, 0xc001505470?, 0xc00062c118?}, 0xc001507410?}}, 0xc00109aa00, {0x1794060?, 0xc0015d0600?, 0x1d21140?}, {0x0, 0x1})
        /usr/lib/go/src/encoding/json/encode.go:760 +0x1f4
encoding/json.(*encodeState).reflectValue(0x0?, {0x1794060?, 0xc0015d0600?, 0x40fba7?}, {0x78?, 0x0?})
        /usr/lib/go/src/encoding/json/encode.go:359 +0x78
encoding/json.(*encodeState).marshal(0xc0015d0600?, {0x1794060?, 0xc0015d0600?}, {0x38?, 0x3e?})
        /usr/lib/go/src/encoding/json/encode.go:331 +0xfa
encoding/json.Marshal({0x1794060, 0xc0015d0600})
        /usr/lib/go/src/encoding/json/encode.go:160 +0x45
github.com/DefiantLabs/cosmos-tax-cli-private/rpc.rpcQueryTx(0x1d23840?, 0x27fa60)
        /home/socket/code/github/DefiantLabs/cosmos-tax-cli-private/rpc/rpc_test.go:209 +0x128
github.com/DefiantLabs/cosmos-tax-cli-private/rpc.TestRPC(0x408639?)
        /home/socket/code/github/DefiantLabs/cosmos-tax-cli-private/rpc/rpc_test.go:88 +0x85
testing.tRunner(0xc0010c61a0, 0x1b6dd28)
        /usr/lib/go/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
        /usr/lib/go/src/testing/testing.go:1493 +0x35f
Resp: 
--- FAIL: TestRPC (2.19s)
    rpc_test.go:85: 
                Error Trace:    rpc_test.go:85
                Error:          Expected nil, but got: &fmt.wrapError{msg:"decoding bech32 failed: invalid bech32 string length 7", err:7}
                Test:           TestRPC
                Messages:       should not error writing to CSV
    rpc_test.go:90: 
                Error Trace:    rpc_test.go:90
                Error:          Expected nil, but got: &json.MarshalerError{Type:(*reflect.rtype)(0x18b2240), Err:(*errors.errorString)(0xc00150aa90), sourceFunc:"MarshalJSON"}
                Test:           TestRPC
                Messages:       should not error calling rpc
2022/11/06 12:12:32 /home/socket/.lens
--- FAIL: TestDecodeIBCTypes (10.00s)
    rpc_test.go:97: 
                Error Trace:    rpc_test.go:97
                Error:          Should be empty, but was post failed: Post "https://osmosis-mainnet-archive.allthatnode.com:26657": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
                Test:           TestDecodeIBCTypes
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x15b0f98]

goroutine 25 [running]:
testing.tRunner.func1.2({0x16dfca0, 0x29e8df0})
        /usr/lib/go/src/testing/testing.go:1396 +0x24e
testing.tRunner.func1()
        /usr/lib/go/src/testing/testing.go:1399 +0x39f
panic({0x16dfca0, 0x29e8df0})
        /usr/lib/go/src/runtime/panic.go:884 +0x212
github.com/DefiantLabs/cosmos-tax-cli-private/rpc.TestDecodeIBCTypes(0xc0014109c0)
        /home/socket/code/github/DefiantLabs/cosmos-tax-cli-private/rpc/rpc_test.go:100 +0x78
testing.tRunner(0xc0014109c0, 0x1b6dd20)
        /usr/lib/go/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
        /usr/lib/go/src/testing/testing.go:1493 +0x35f
FAIL    github.com/DefiantLabs/cosmos-tax-cli-private/rpc       12.230s
?       github.com/DefiantLabs/cosmos-tax-cli-private/tasks     [no test files]
2022/11/06 12:12:29 proto: duplicate proto type registered: ibc.applications.transfer.v1.DenomTrace
2022/11/06 12:12:29 proto: duplicate proto type registered: ibc.applications.transfer.v1.Params
2022/11/06 12:12:29 proto: duplicate proto type registered: ibc.applications.transfer.v1.MsgTransfer
2022/11/06 12:12:29 proto: duplicate proto type registered: ibc.applications.transfer.v1.MsgTransferResponse
--- FAIL: TestOsmosisCsvForAddress (0.00s)
    indexer_test.go:21: Error getting config. Err: open ../config.toml: no such file or directory
--- FAIL: TestCsvForAddress (0.00s)
    indexer_test.go:47: Error getting config. Err: open ../config.toml: no such file or directory
Error opening configuration file open ../config.toml: no such file or directory
--- FAIL: TestLookupTxForAddresses (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1463eb8]

goroutine 25 [running]:
testing.tRunner.func1.2({0x16f5540, 0x2a02ad0})
        /usr/lib/go/src/testing/testing.go:1396 +0x24e
testing.tRunner.func1()
        /usr/lib/go/src/testing/testing.go:1399 +0x39f
panic({0x16f5540, 0x2a02ad0})
        /usr/lib/go/src/runtime/panic.go:884 +0x212
gorm.io/gorm.(*DB).getInstance(0x0?)
        /home/socket/go/pkg/mod/gorm.io/gorm@v1.23.6/gorm.go:363 +0x18
gorm.io/gorm.(*DB).Joins(0x0?, {0x1992078, 0x6e}, {0x0?, 0x0, 0x0})
        /home/socket/go/pkg/mod/gorm.io/gorm@v1.23.6/chainable_api.go:186 +0x58
github.com/DefiantLabs/cosmos-tax-cli-private/db.GetTaxableTransactions({0x19475dc, 0x2b}, 0x18fd22c?)
        /home/socket/code/github/DefiantLabs/cosmos-tax-cli-private/db/search.go:11 +0x5c
github.com/DefiantLabs/cosmos-tax-cli-private/test.TestLookupTxForAddresses(0xc0012c8000)
        /home/socket/code/github/DefiantLabs/cosmos-tax-cli-private/test/indexer_test.go:78 +0x4e
testing.tRunner(0xc0012c8000, 0x1b82ab8)
        /usr/lib/go/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
        /usr/lib/go/src/testing/testing.go:1493 +0x35f
FAIL    github.com/DefiantLabs/cosmos-tax-cli-private/test      0.038s
?       github.com/DefiantLabs/cosmos-tax-cli-private/util      [no test files]
FAIL

go-test-repo-mod.........................................................Failed
- hook id: go-test-repo-mod
- exit code: 1

2022/11/06 12:12:43 proto: duplicate proto type registered: ibc.applications.transfer.v1.DenomTrace
2022/11/06 12:12:43 proto: duplicate proto type registered: ibc.applications.transfer.v1.Params
2022/11/06 12:12:43 proto: duplicate proto type registered: ibc.applications.transfer.v1.MsgTransfer
2022/11/06 12:12:43 proto: duplicate proto type registered: ibc.applications.transfer.v1.MsgTransferResponse
--- FAIL: TestCosmosHubAddressEquality (0.00s)
    backend_test.go:25: Addresses not equivalent invalid Bech32 prefix; expected osmo, got cosmos invalid Bech32 prefix; expected osmovaloper, got cosmosvaloper
--- FAIL: TestCosmosAllAddressEquality (0.00s)
    backend_test.go:37: Addresses not equivalent <nil> <nil>
FAIL
FAIL    github.com/DefiantLabs/cosmos-tax-cli-private   0.032s
?       github.com/DefiantLabs/cosmos-tax-cli-private/client    [no test files]
?       github.com/DefiantLabs/cosmos-tax-cli-private/cmd       [no test files]
?       github.com/DefiantLabs/cosmos-tax-cli-private/config    [no test files]
?       github.com/DefiantLabs/cosmos-tax-cli-private/core      [no test files]
?       github.com/DefiantLabs/cosmos-tax-cli-private/cosmos/modules    [no test files]
?       github.com/DefiantLabs/cosmos-tax-cli-private/cosmos/modules/bank       [no test files]
?       github.com/DefiantLabs/cosmos-tax-cli-private/cosmos/modules/denoms     [no test files]
?       github.com/DefiantLabs/cosmos-tax-cli-private/cosmos/modules/distribution       [no test files]
?       github.com/DefiantLabs/cosmos-tax-cli-private/cosmos/modules/ibc        [no test files]
?       github.com/DefiantLabs/cosmos-tax-cli-private/cosmos/modules/ibc/types  [no test files]
?       github.com/DefiantLabs/cosmos-tax-cli-private/cosmos/modules/staking    [no test files]
?       github.com/DefiantLabs/cosmos-tax-cli-private/cosmos/modules/tx [no test files]
ok      github.com/DefiantLabs/cosmos-tax-cli-private/csv       (cached)
?       github.com/DefiantLabs/cosmos-tax-cli-private/csv/parsers       [no test files]
?       github.com/DefiantLabs/cosmos-tax-cli-private/csv/parsers/accointing    [no test files]
?       github.com/DefiantLabs/cosmos-tax-cli-private/db        [no test files]
?       github.com/DefiantLabs/cosmos-tax-cli-private/osmosis   [no test files]
ok      github.com/DefiantLabs/cosmos-tax-cli-private/osmosis/modules/gamm      (cached)
?       github.com/DefiantLabs/cosmos-tax-cli-private/rest      [no test files]
2022/11/06 12:12:43 proto: duplicate proto type registered: ibc.applications.transfer.v1.DenomTrace
2022/11/06 12:12:43 proto: duplicate proto type registered: ibc.applications.transfer.v1.Params
2022/11/06 12:12:43 proto: duplicate proto type registered: ibc.applications.transfer.v1.MsgTransfer
2022/11/06 12:12:43 proto: duplicate proto type registered: ibc.applications.transfer.v1.MsgTransferResponse
2022/11/06 12:12:43 /home/socket/.lens
2022/11/06 12:12:43 Error getting account from key or address:  default
2022/11/06 12:12:43 /home/socket/.lens
goroutine 15 [running]:
runtime/debug.Stack()
        /usr/lib/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /usr/lib/go/src/runtime/debug/stack.go:16 +0x19
github.com/cosmos/cosmos-sdk/codec/types.anyCompatError({0x18edd2b, 0xc}, {0x18b2240, 0xc0002bcfc0})
        /home/socket/go/pkg/mod/github.com/osmosis-labs/cosmos-sdk@v0.45.1-0.20220502203419-5831ca02b81f/codec/types/compat.go:24 +0x3f
github.com/cosmos/cosmos-sdk/codec/types.(*Any).MarshalJSON(0x18b2240?)
        /home/socket/go/pkg/mod/github.com/osmosis-labs/cosmos-sdk@v0.45.1-0.20220502203419-5831ca02b81f/codec/types/compat.go:56 +0x56
encoding/json.marshalerEncoder(0xc0005f0b80, {0x18b2240?, 0xc0000141e0?, 0x185a0a0?}, {0x40?, 0xcb?})
        /usr/lib/go/src/encoding/json/encode.go:478 +0xbe
encoding/json.arrayEncoder.encode({0xc000fbdb10?}, 0xc0005f0b80, {0x1641be0?, 0xc0002bcf60?, 0x16ad130?}, {0xa?, 0x0?})
        /usr/lib/go/src/encoding/json/encode.go:915 +0xd5
encoding/json.sliceEncoder.encode({0x0?}, 0xc0005f0b80, {0x1641be0?, 0xc0002bcf60?, 0x0?}, {0xb?, 0x0?})
        /usr/lib/go/src/encoding/json/encode.go:888 +0x367
encoding/json.structEncoder.encode({{{0xc000634000?, 0x1?, 0x0?}, 0xc000158b10?}}, 0xc0005f0b80, {0x17ebfe0?, 0xc0002bcf60?, 0x10?}, {0x0, 0x1})
        /usr/lib/go/src/encoding/json/encode.go:760 +0x1f4
encoding/json.ptrEncoder.encode({0x175ace0?}, 0xc0005f0b80, {0x1892740?, 0xc0001583f0?, 0x3?}, {0x7?, 0x0?})
        /usr/lib/go/src/encoding/json/encode.go:944 +0x25e
encoding/json.structEncoder.encode({{{0xc000d9d200?, 0x0?, 0x0?}, 0xc000158e70?}}, 0xc0005f0b80, {0x17941e0?, 0xc0001583f0?, 0x0?}, {0x0, 0x1})
        /usr/lib/go/src/encoding/json/encode.go:760 +0x1f4
encoding/json.ptrEncoder.encode({0xc000f060c0?}, 0xc0005f0b80, {0x18ab880?, 0xc001778200?, 0x7?}, {0x30?, 0x0?})
        /usr/lib/go/src/encoding/json/encode.go:944 +0x25e
encoding/json.arrayEncoder.encode({0x8?}, 0xc0005f0b80, {0x16420e0?, 0xc001779ac0?, 0xc000fbdb08?}, {0x86?, 0x16?})
        /usr/lib/go/src/encoding/json/encode.go:915 +0xd5
encoding/json.sliceEncoder.encode({0x4690da?}, 0xc0005f0b80, {0x16420e0?, 0xc001779ac0?, 0xc0005f0b80?}, {0x6?, 0x0?})
        /usr/lib/go/src/encoding/json/encode.go:888 +0x367
encoding/json.structEncoder.encode({{{0xc000d9cb40?, 0xc000efca30?, 0xc000014288?}, 0xc000159410?}}, 0xc0005f0b80, {0x1794060?, 0xc001779ac0?, 0x1d21140?}, {0x0, 0x1})
        /usr/lib/go/src/encoding/json/encode.go:760 +0x1f4
encoding/json.(*encodeState).reflectValue(0x0?, {0x1794060?, 0xc001779ac0?, 0x40fba7?}, {0x78?, 0x0?})
        /usr/lib/go/src/encoding/json/encode.go:359 +0x78
encoding/json.(*encodeState).marshal(0xc001779ac0?, {0x1794060?, 0xc001779ac0?}, {0x38?, 0xbe?})
        /usr/lib/go/src/encoding/json/encode.go:331 +0xfa
encoding/json.Marshal({0x1794060, 0xc001779ac0})
        /usr/lib/go/src/encoding/json/encode.go:160 +0x45
github.com/DefiantLabs/cosmos-tax-cli-private/rpc.rpcQueryTx(0x1d23840?, 0x27fa60)
        /home/socket/code/github/DefiantLabs/cosmos-tax-cli-private/rpc/rpc_test.go:209 +0x128
github.com/DefiantLabs/cosmos-tax-cli-private/rpc.TestRPC(0x0?)
        /home/socket/code/github/DefiantLabs/cosmos-tax-cli-private/rpc/rpc_test.go:88 +0x85
testing.tRunner(0xc0011c3ba0, 0x1b6dd28)
        /usr/lib/go/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
        /usr/lib/go/src/testing/testing.go:1493 +0x35f
Resp: 
--- FAIL: TestRPC (0.61s)
    rpc_test.go:85: 
                Error Trace:    rpc_test.go:85
                Error:          Expected nil, but got: &fmt.wrapError{msg:"decoding bech32 failed: invalid bech32 string length 7", err:7}
                Test:           TestRPC
                Messages:       should not error writing to CSV
    rpc_test.go:90: 
                Error Trace:    rpc_test.go:90
                Error:          Expected nil, but got: &json.MarshalerError{Type:(*reflect.rtype)(0x18b2240), Err:(*errors.errorString)(0xc0002f4c00), sourceFunc:"MarshalJSON"}
                Test:           TestRPC
                Messages:       should not error calling rpc
2022/11/06 12:12:43 /home/socket/.lens
FAIL
FAIL    github.com/DefiantLabs/cosmos-tax-cli-private/rpc       1.225s
?       github.com/DefiantLabs/cosmos-tax-cli-private/tasks     [no test files]
2022/11/06 12:12:43 proto: duplicate proto type registered: ibc.applications.transfer.v1.DenomTrace
2022/11/06 12:12:43 proto: duplicate proto type registered: ibc.applications.transfer.v1.Params
2022/11/06 12:12:43 proto: duplicate proto type registered: ibc.applications.transfer.v1.MsgTransfer
2022/11/06 12:12:43 proto: duplicate proto type registered: ibc.applications.transfer.v1.MsgTransferResponse
--- FAIL: TestOsmosisCsvForAddress (0.00s)
    indexer_test.go:21: Error getting config. Err: open ../config.toml: no such file or directory
--- FAIL: TestCsvForAddress (0.00s)
    indexer_test.go:47: Error getting config. Err: open ../config.toml: no such file or directory
Error opening configuration file open ../config.toml: no such file or directory
--- FAIL: TestLookupTxForAddresses (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1463eb8]

goroutine 24 [running]:
testing.tRunner.func1.2({0x16f5540, 0x2a02ad0})
        /usr/lib/go/src/testing/testing.go:1396 +0x24e
testing.tRunner.func1()
        /usr/lib/go/src/testing/testing.go:1399 +0x39f
panic({0x16f5540, 0x2a02ad0})
        /usr/lib/go/src/runtime/panic.go:884 +0x212
gorm.io/gorm.(*DB).getInstance(0x0?)
        /home/socket/go/pkg/mod/gorm.io/gorm@v1.23.6/gorm.go:363 +0x18
gorm.io/gorm.(*DB).Joins(0x0?, {0x1992078, 0x6e}, {0x0?, 0x0, 0x0})
        /home/socket/go/pkg/mod/gorm.io/gorm@v1.23.6/chainable_api.go:186 +0x58
github.com/DefiantLabs/cosmos-tax-cli-private/db.GetTaxableTransactions({0x19475dc, 0x2b}, 0x18fd22c?)
        /home/socket/code/github/DefiantLabs/cosmos-tax-cli-private/db/search.go:11 +0x5c
github.com/DefiantLabs/cosmos-tax-cli-private/test.TestLookupTxForAddresses(0xc0010f36c0)
        /home/socket/code/github/DefiantLabs/cosmos-tax-cli-private/test/indexer_test.go:78 +0x4e
testing.tRunner(0xc0010f36c0, 0x1b82ab8)
        /usr/lib/go/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
        /usr/lib/go/src/testing/testing.go:1493 +0x35f
FAIL    github.com/DefiantLabs/cosmos-tax-cli-private/test      0.034s
?       github.com/DefiantLabs/cosmos-tax-cli-private/util      [no test files]
FAIL

go-revive................................................................Passed
go-revive-mod............................................................Passed
go-revive-repo-mod.......................................................Passed
```

**Comment by danbryan** [comment]
cc @jtieri this is similar to the notion go best practices one.  The gist of all the tickets, is i want to follow best practices as this is an open souce tool, and we want to encourage people to contribute to it.  We don't have to be soo picky about checks it becomes a PITA to work on this, but i think we should set some reasonable standards and practices.

**Comment by jtieri** [comment]
> cc @jtieri this is similar to the notion go best practices one. The gist of all the tickets, is i want to follow best practices as this is an open souce tool, and we want to encourage people to contribute to it. We don't have to be soo picky about checks it becomes a PITA to work on this, but i think we should set some reasonable standards and practices.

Understood. I think the current pre-hooks are nice and once we get all the linter issues fixed it should be smooth sailing moving forward. The current configuration for the linter is similar to what's used in all of the Cosmos repos. Should at least ensure that the code styling and conventions are somewhat sane without being too burdensome.

**Comment by danbryan** [comment]
@jtieri can this be closed?

**Comment by jtieri** [comment]
no these tests are still failing, tbh the testing situation is a bit of a mess and i havent taken the time to dig into it much because it doesnt seem to be the most pressing issue.

**Comment by danbryan** [comment]
yeah, definitely want to get IBC transfers supported first, then we can come back to this.

**Comment by danbryan** [comment]
gonna remove from sprint for the time being
